image: rust

stages:
  - test
  - publish

test:
  stage: test
  script: cargo test

publish:
  stage: publish
  before_script:
    - cargo login $CARGO_TOKEN
  script: cargo publish
  only:
    - tags
