[package]
name = "fuzzy-tree"
version = "0.1.0"
authors = ["Lewis Belcher <belcher_lewis@protonmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
env_logger = "0.7.1"
lazy_static = "1.4"
log = "0.4"
termion = "1.5.5"

[[bin]]
name = "fztree"
path = "src/main.rs"
